
GET http://localhost:3000/author/firstName/Naftaly

###
GET http://localhost:3000/author/filter

###
GET http://localhost:3000/books/Description/Third

###
GET http://localhost:3000/books/pages/250

###

POST http://localhost:4000/api/tacher
Content-Type: application/json

{
      "tName": "jhon Cohen",
      "ages":35,
      "professionType":"english",
      "idNum":  1770
}

###

POST http://localhost:3000/books/create
Content-Type: application/json

{
    "bookName": "how to beat covid19",
    "bookDescription": "finish wit the covid19",
    "publicationDate": "2021",
    "author": "Naftaly Benet ",
    "pagesNumbers":275
}

###

GET http://localhost:5000/api/tacher